apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: cloud-native-notes
data:
  APP_NAME: "Cloud Native Notes"
  LOG_LEVEL: "info"
  MAX_NOTES: "100"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
